;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	counsel-M-x
	keyboard-escape-quit
	))

(setq mc/cmds-to-run-once
      '(
	eval-print-last-sexp
	hungry-delete-backward
	indent-new-comment-line
	ns-paste-secondary
	org-return-indent
	upcase-region
	))
